#!/bin/bash

echo "display path"
echo "$(pwd)"
echo "display dockerfile path"
echo $DOCKERFILE_PATH
cd ..
echo "display path"
echo "$(pwd)"
echo "current branch"
echo "$SOURCE_BRANCH"

version_regex='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
if [[ "$SOURCE_BRANCH" == "main" || "$SOURCE_BRANCH" =~ $version_regex ]]; then
  echo "The branch is main, proceeding with multi-arch build"
  docker buildx create --name multiarch --use
  docker buildx build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" --platform linux/arm64,linux/amd64 --push .
else
  echo "The branch is not main, proceeding with classic build"
  docker buildx build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" --push .
fi