#!/bin/bash

echo "display path"
echo "$(pwd)"
echo "display dockerfile path"
echo $DOCKERFILE_PATH
cd ..
echo "display path"
echo "$(pwd)"
docker buildx create --name multiarch --use --driver=docker-container
docker buildx build --driver docker-container -f $DOCKERFILE_PATH -t $IMAGE_NAME --platform linux/arm64 --push .