# Generated by Django 3.2.10 on 2021-12-25 15:19

from datetime import datetime

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="IOC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("type", models.CharField(max_length=32)),
                (
                    "first_seen",
                    models.DateTimeField(blank=False, default=datetime.utcnow),
                ),
                (
                    "last_seen",
                    models.DateTimeField(blank=False, default=datetime.utcnow),
                ),
                (
                    "days_seen",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(), size=None, default=list
                    ),
                ),
                ("number_of_days_seen", models.IntegerField(default=1)),
                ("times_seen", models.IntegerField(default=1)),
                (
                    "honeypots",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=900),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "attack_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        size=None,
                        default=list,
                    ),
                ),
                (
                    "related_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=900),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "related_ioc",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_greedybear_ioc_related_ioc_+",
                        to="greedybear.IOC",
                    ),
                ),
            ],
        ),
    ]
