# Generated by Django 3.2.10 on 2021-12-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ioc",
            name="cowrie",
            field=models.BooleanField(default=False),
        ),
    ]
