# Generated by Django 3.2.14 on 2022-07-20 11:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0002_ioc_cowrie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=15)),
                ("feeds_api", models.BooleanField(default=False)),
                ("enrichment_view_api", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
