# Generated by Django 3.2.14 on 2022-07-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0003_statistics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statistics",
            old_name="date",
            new_name="request_date",
        ),
    ]
