# Generated by Django 3.2.15 on 2022-11-24 07:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0005_clients"),
    ]

    operations = [
        migrations.AddField(
            model_name="ioc",
            name="general",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=32),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
