# Generated by Django 4.2.15 on 2024-12-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0009_alter_ioc_general_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ioc",
            name="related_ioc",
            field=models.ManyToManyField(blank=True, to="greedybear.ioc"),
        ),
    ]
