# Generated by Django 4.2.15 on 2024-12-02 16:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0010_alter_ioc_related_ioc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='asn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ioc',
            name='destination_ports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='ioc',
            name='ip_reputation',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ioc',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CowrieSession',
            fields=[
                ('session_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('login_attempt', models.BooleanField(default=False)),
                ('command_execution', models.BooleanField(default=False)),
                ('interaction_count', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greedybear.ioc')),
            ],
        ),
    ]
