# Generated by Django 4.2.15 on 2024-12-13 17:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0010_alter_ioc_related_ioc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ioc",
            old_name="times_seen",
            new_name="attack_count",
        ),
        migrations.AddField(
            model_name="ioc",
            name="asn",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ioc",
            name="destination_ports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="ioc",
            name="interaction_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ioc",
            name="ip_reputation",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="ioc",
            name="login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ioc",
            name="days_seen",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(), blank=True, default=list, size=None
            ),
        ),
        migrations.CreateModel(
            name="CowrieSession",
            fields=[
                (
                    "session_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("login_attempt", models.BooleanField(default=False)),
                (
                    "credentials",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=256),
                        default=list,
                        size=None,
                    ),
                ),
                ("command_execution", models.BooleanField(default=False)),
                ("interaction_count", models.IntegerField(default=0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="greedybear.ioc"
                    ),
                ),
            ],
        ),
    ]
