# Generated by Django 4.2.15 on 2025-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0012_auto_20241213_1743"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ioc",
            index=models.Index(fields=["name"], name="greedybear__name_b54897_idx"),
        ),
    ]
