# Generated by Django 4.2.15 on 2025-02-10 12:58

from django.db import migrations


def removeDdospot(apps, schema_editor):
    GeneralHoneypot = apps.get_model("greedybear", "GeneralHoneypot")
    try:
        ddospot = GeneralHoneypot.objects.get(name__iexact="Ddospot")
        IOC = apps.get_model("greedybear", "IOC")
        # do nothing if Ddospot is in active use
        if ddospot.active and IOC.objects.filter(general_honeypot=ddospot).exists():
            return
        ddospot.delete()
    except GeneralHoneypot.DoesNotExist as e:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0013_ioc_greedybear__name_b54897_idx"),
    ]

    operations = [migrations.RunPython(removeDdospot)]
