# Generated by Django 4.2.17 on 2025-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0014_auto_20250210_1258"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cowriesession",
            index=models.Index(fields=["source"], name="greedybear__source__a3720f_idx"),
        ),
    ]
