# Generated by Django 4.2.17 on 2025-02-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0015_cowriesession_greedybear__source__a3720f_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="ioc",
            name="expected_interactions",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="ioc",
            name="recurrence_probability",
            field=models.FloatField(default=0, null=True),
        ),
    ]
