# Generated by Django 4.2.17 on 2025-02-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0016_ioc_expected_interactions_ioc_recurrence_probability"),
    ]

    operations = [
        migrations.AddField(
            model_name="ioc",
            name="threat_level",
            field=models.FloatField(default=0, null=True),
        ),
    ]
