# Generated by Django 4.2.17 on 2025-02-21 07:26

import datetime

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0016_ioc_expected_interactions_ioc_recurrence_probability"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_seen", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("last_seen", models.DateTimeField(default=datetime.datetime.utcnow)),
                (
                    "commands",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=1024),
                        default=list,
                        size=None,
                    ),
                ),
                ("commands_hash", models.CharField(blank=True, max_length=64)),
                ("cluster", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="cowriesession",
            name="commands",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="greedybear.commandsequence",
            ),
        ),
    ]
