# Generated by Django 4.2.17 on 2025-02-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0017_commandsequence_cowriesession_commands"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandsequence",
            name="commands_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
