# Generated by Django 4.2.20 on 2025-04-08 20:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0018_alter_commandsequence_commands_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandsequence",
            name="first_seen",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="commandsequence",
            name="last_seen",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="ioc",
            name="first_seen",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="ioc",
            name="last_seen",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="request_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="view",
            field=models.CharField(
                choices=[("feeds", "Feeds View"), ("enrichment", "Enrichment View"), ("command sequence", "Command Sequence View")],
                default="feeds",
                max_length=32,
            ),
        ),
    ]
