# Generated by Django 4.2.20 on 2025-07-13 17:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0019_alter_commandsequence_first_seen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MassScanners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=256)),
                ("added", models.DateTimeField(default=datetime.datetime.now)),
                ("reason", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
