# Generated by Django 4.2.20 on 2025-07-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0020_massscanners"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="massscanners",
            index=models.Index(fields=["ip_address"], name="greedybear__ip_addr_2aa484_idx"),
        ),
    ]
