# Generated by Django 4.2.20 on 2025-07-18 17:45

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0021_massscanners_greedybear__ip_addr_2aa484_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsMyIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=256)),
                ("added", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["domain"], name="greedybear__domain_f89b04_idx"
                    )
                ],
            },
        ),
    ]
