# Generated by Django 5.2.8 on 2025-12-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0022_whatsmyip"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MassScanners",
            new_name="MassScanner",
        ),
        migrations.RenameModel(
            old_name="Sensors",
            new_name="Sensor",
        ),
        migrations.RenameModel(
            old_name="WhatsMyIP",
            new_name="WhatsMyIPDomain",
        ),
        migrations.RenameIndex(
            model_name="massscanner",
            new_name="greedybear__ip_addr_3c3fd4_idx",
            old_name="greedybear__ip_addr_2aa484_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsmyipdomain",
            new_name="greedybear__domain_7f23b0_idx",
            old_name="greedybear__domain_f89b04_idx",
        ),
        migrations.AlterField(
            model_name="statistics",
            name="view",
            field=models.CharField(
                choices=[
                    ("feeds", "Feeds View"),
                    ("enrichment", "Enrichment View"),
                    ("command sequence", "Command Sequence View"),
                    ("cowrie session", "Cowrie Session View"),
                ],
                default="feeds",
                max_length=32,
            ),
        ),
    ]
