# Generated by Django on 2025-12-15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0022_whatsmyip"),
    ]

    operations = [
        migrations.CreateModel(
            name="TorExitNodes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.CharField(max_length=256)),
                ("added", models.DateTimeField(default=datetime.datetime.now)),
                ("reason", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["ip_address"], name="greedybear__torexit_ip_addr_idx")],
            },
        ),
    ]
