# Generated by Django 5.2.8 on 2025-12-22 11:24

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0022_whatsmyip"),
    ]

    operations = [
        migrations.AddField(
            model_name="ioc",
            name="firehol_categories",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="view",
            field=models.CharField(
                choices=[
                    ("feeds", "Feeds View"),
                    ("enrichment", "Enrichment View"),
                    ("command sequence", "Command Sequence View"),
                    ("cowrie session", "Cowrie Session View"),
                ],
                default="feeds",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="FireHolList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.CharField(max_length=256)),
                ("added", models.DateTimeField(default=datetime.datetime.now)),
                ("source", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["ip_address"], name="greedybear__ip_addr_e01f2f_idx")],
            },
        ),
    ]
