# Generated by Django on 2025-12-15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0023_torexitnodes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.CharField(max_length=256)),
                ("ioc", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to="greedybear.ioc")),
                ("source", models.CharField(max_length=128)),
                ("tag", models.CharField(max_length=256)),
                ("added", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "indexes": [models.Index(fields=["ip_address"], name="greedybear__enrich_ip_addr_idx")],
            },
        ),
    ]
