# Generated by Django 5.2.8 on 2025-12-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0023_ioc_firehol_categories_alter_statistics_view_and_more"),
        ("greedybear", "0023_rename_massscanners_massscanner_and_more"),
    ]

    operations = []
