# Generated by Django 5.2.8 on 2025-12-23

from django.db import migrations


def migrate_honeypots_forward(apps, schema_editor):
    """
    Migrate IOC.cowrie and IOC.log4j boolean fields to GeneralHoneypot M2M entries.

    This migration:
    1. Creates 'Cowrie' and 'Log4Pot' entries in GeneralHoneypot table if they don't exist
    2. For each IOC with cowrie=True, adds the Cowrie GeneralHoneypot entry
    3. For each IOC with log4j=True, adds the Log4Pot GeneralHoneypot entry
    """
    IOC = apps.get_model("greedybear", "IOC")
    GeneralHoneypot = apps.get_model("greedybear", "GeneralHoneypot")

    # Create or get the GeneralHoneypot entries for Cowrie and Log4Pot
    cowrie_hp, _ = GeneralHoneypot.objects.get_or_create(
        name="Cowrie", defaults={"active": True}
    )
    log4pot_hp, _ = GeneralHoneypot.objects.get_or_create(
        name="Log4Pot", defaults={"active": True}
    )

    # Migrate Cowrie IOCs - using iterator for memory efficiency with large datasets
    for ioc in IOC.objects.filter(cowrie=True).iterator():
        ioc.general_honeypot.add(cowrie_hp)

    # Migrate Log4Pot IOCs (the field is named 'log4j' in the model)
    for ioc in IOC.objects.filter(log4j=True).iterator():
        ioc.general_honeypot.add(log4pot_hp)


def migrate_honeypots_reverse(apps, schema_editor):
    """
    Reverse migration: restore boolean field values from GeneralHoneypot M2M entries.

    This allows rolling back the migration if needed.
    """
    IOC = apps.get_model("greedybear", "IOC")
    GeneralHoneypot = apps.get_model("greedybear", "GeneralHoneypot")

    try:
        cowrie_hp = GeneralHoneypot.objects.get(name="Cowrie")
        IOC.objects.filter(general_honeypot=cowrie_hp).update(cowrie=True)
    except GeneralHoneypot.DoesNotExist:
        pass

    try:
        log4pot_hp = GeneralHoneypot.objects.get(name="Log4Pot")
        IOC.objects.filter(general_honeypot=log4pot_hp).update(log4j=True)
    except GeneralHoneypot.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0023_rename_massscanners_massscanner_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_honeypots_forward, migrate_honeypots_reverse),
    ]
