# Generated by Django 5.2.8 on 2025-12-23 01:09

from django.db import migrations


def migrate_honeypots(apps, schema_editor):
    IOC = apps.get_model("greedybear", "IOC")
    GeneralHoneypot = apps.get_model("greedybear", "GeneralHoneypot")

    # Create or get the GeneralHoneypot entries
    cowrie_gh, _ = GeneralHoneypot.objects.get_or_create(name="Cowrie", defaults={"active": True})
    log4pot_gh, _ = GeneralHoneypot.objects.get_or_create(name="Log4Pot", defaults={"active": True})

    # Migrate Cowrie IOCs
    # Using iterator to handle potential large datasets efficiently
    for ioc in IOC.objects.filter(cowrie=True).iterator():
        ioc.general_honeypot.add(cowrie_gh)

    # Migrate Log4Pot IOCs (using the field 'log4j' which corresponds to Log4Pot honeypot)
    for ioc in IOC.objects.filter(log4j=True).iterator():
        ioc.general_honeypot.add(log4pot_gh)


def reverse_migrate_honeypots(apps, schema_editor):
    IOC = apps.get_model("greedybear", "IOC")
    GeneralHoneypot = apps.get_model("greedybear", "GeneralHoneypot")

    try:
        cowrie_gh = GeneralHoneypot.objects.get(name="Cowrie")
        # Initialize queryset to update
        # We need to verify if the 'cowrie' field still exists when this reverse runs
        # If this runs before the field removal migration is reversed, the field might not be there?
        # No, reverse order ensures field is added back before this runs if we order migrations correctly.
        # But here we are ONLY doing data migration. The field removal is NEXT migration.
        # So fields exist.
        IOC.objects.filter(general_honeypot=cowrie_gh).update(cowrie=True)
    except GeneralHoneypot.DoesNotExist:
        pass

    try:
        log4pot_gh = GeneralHoneypot.objects.get(name="Log4Pot")
        IOC.objects.filter(general_honeypot=log4pot_gh).update(log4j=True)
    except GeneralHoneypot.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0022_whatsmyip"),
    ]

    operations = [
        migrations.RunPython(migrate_honeypots, reverse_migrate_honeypots),
    ]
