# Generated by Django 5.2.8 on 2025-12-23 21:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    Merge migration for two parallel 0024 migrations:
    - 0024_ioc_firehol_categories_alter_statistics_view_and_more (upstream firehol changes)
    - 0024_migrate_honeypot_data (honeypot unification M2M migration)
    """

    dependencies = [
        ("greedybear", "0024_ioc_firehol_categories_alter_statistics_view_and_more"),
        ("greedybear", "0024_migrate_honeypot_data"),
    ]

    operations = []
