# Generated by Django 5.2.8 on 2025-12-23 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0024_migrate_honeypot_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ioc",
            name="cowrie",
        ),
        migrations.RemoveField(
            model_name="ioc",
            name="log4j",
        ),
    ]
