# Generated by Django 5.2.8 on 2025-12-23

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove legacy cowrie and log4j boolean fields from IOC model.

    These fields have been replaced by the general_honeypot ManyToManyField
    relationship to GeneralHoneypot entries. The data migration (0024)
    should have already copied the boolean values to the M2M relationship.
    """

    dependencies = [
        ("greedybear", "0024_migrate_honeypot_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ioc",
            name="cowrie",
        ),
        migrations.RemoveField(
            model_name="ioc",
            name="log4j",
        ),
    ]
