# Generated by Django 5.2.8 on 2026-01-01 00:00

from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0025_merge_20251223_2100"),
    ]

    operations = [
        migrations.CreateModel(
            name="TorExitNodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=256)),
                ("added", models.DateTimeField(default=datetime.now)),
            ],
        ),
        migrations.AddIndex(
            model_name="torexitnodes",
            index=models.Index(fields=["ip_address"], name="greedybear__ip_addr_tor_idx"),
        ),
    ]
