# Generated by Django 5.2.9 on 2026-01-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0026_remove_legacy_honeypot_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firehollist",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="massscanner",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
