# Generated by Django 5.2.10

from django.db import migrations


def remove_hardcoded_honeypots(apps, schema_editor):
    """
    Remove hard-coded honeypots from migration 0008 if they are not in use.

    Only deletes honeypots with no associated IOC data .
    """
    GeneralHoneypot = apps.get_model("greedybear", "GeneralHoneypot")
    IOC = apps.get_model("greedybear", "IOC")

    # The 15 honeypots that were hard-coded in migration 0008
    old_honeypots = [
        "Heralding",
        "Ciscoasa",
        "Honeytrap",
        "Dionaea",
        "ConPot",
        "Adbhoney",
        "Tanner",
        "CitrixHoneypot",
        "Mailoney",
        "Ipphoney",
        "Ddospot",
        "ElasticPot",
        "Dicompot",
        "Redishoneypot",
        "Sentrypeer",
        "Glutton",
    ]

    for hp_name in old_honeypots:
        try:
            honeypot = GeneralHoneypot.objects.get(name=hp_name)
            # Only delete if NOT in use (no IOCs associated with this honeypot)
            if not IOC.objects.filter(general_honeypot=honeypot).exists():
                honeypot.delete()
        except GeneralHoneypot.DoesNotExist:
            # Honeypot doesn't exist, nothing to delete
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0027_disable_unwanted_honeypots"),
    ]

    operations = [
        migrations.RunPython(
            remove_hardcoded_honeypots,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
