# Generated by Django 5.2.8 on 2026-01-09 15:53

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0027_disable_unwanted_honeypots"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="generalhoneypot",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_generalhoneypot_name_ci",
            ),
        ),
    ]
