# Generated by Django 5.2.10 on 2026-01-26 10:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0031_remove_cowrie_log4j_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TorExitNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=256, unique=True)),
                ("added", models.DateTimeField(default=datetime.datetime.now)),
                ("reason", models.CharField(blank=True, default="tor exit node", max_length=64)),
            ],
        ),
        migrations.AddIndex(
            model_name="torexitnode",
            index=models.Index(fields=["ip_address"], name="greedybear_ip_addr_tor_idx"),
        ),
    ]
