# Generated by Django 4.2.20
# This file is a part of GreedyBear https://github.com/honeynet/GreedyBear
# See the file 'LICENSE' for copying permission.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0032_torexitnode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CowrieCredential",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, max_length=256)),
                ("password", models.CharField(blank=True, max_length=256)),
                (
                    "session",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_set",
                        to="greedybear.cowriesession",
                    ),
                ),
            ],
            options={
                "db_table": "greedybear_cowriecredential",
            },
        ),
        migrations.AddIndex(
            model_name="cowriecredential",
            index=models.Index(fields=["password"], name="cowriecred_pass_idx"),
        ),
        migrations.AddIndex(
            model_name="cowriecredential",
            index=models.Index(fields=["username", "password"], name="cowriecred_user_pass_idx"),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX cowriecred_pass_lower_idx ON greedybear_cowriecredential(LOWER(password));",
            reverse_sql="DROP INDEX IF EXISTS cowriecred_pass_lower_idx;",
        ),
    ]
