# Generated by Django 5.2.10 on 2026-01-27 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0032_torexitnode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("source", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ioc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="greedybear.ioc",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["ioc", "source"], name="greedybear_tag_ioc_source_idx"),
        ),
    ]
