# Generated by Django 5.2.10 on 2026-02-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0033_disable_additional_honeypots'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='torexitnode',
            new_name='greedybear__ip_addr_6bc095_idx',
            old_name='greedybear_ip_addr_tor_idx',
        ),
        migrations.AddField(
            model_name='ioc',
            name='attacker_country_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='ioc',
            name='attacker_country_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ioc',
            name='sensor_country_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='ioc',
            name='sensor_country_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
