# Generated by Django 5.2.11 on 2026-02-11 21:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0033_disable_additional_honeypots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralHoneypot',
            new_name='Honeypot',
        ),
        migrations.RemoveConstraint(
            model_name='honeypot',
            name='unique_generalhoneypot_name_ci',
        ),
        migrations.RenameIndex(
            model_name='torexitnode',
            new_name='greedybear__ip_addr_6bc095_idx',
            old_name='greedybear_ip_addr_tor_idx',
        ),
        migrations.AddConstraint(
            model_name='honeypot',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_honeypot_name_ci'),
        ),
    ]
