# Generated by Django 5.2.10 on 2026-02-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0034_remove_unused_log4pot'),
        ('greedybear', '0034_rename_greedybear_ip_addr_tor_idx_greedybear__ip_addr_6bc095_idx_and_more'),
    ]

    operations = [
    ]
