# Generated by Django 5.2.10 on 2026-02-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0034_rename_greedybear_ip_addr_tor_idx_greedybear__ip_addr_6bc095_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ioc',
            name='sensor_country_code',
        ),
        migrations.RemoveField(
            model_name='ioc',
            name='sensor_country_name',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_country_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_country_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
