# Generated by Django 5.2.11 on 2026-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0034_remove_unused_log4pot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='torexitnode',
            new_name='greedybear__ip_addr_6bc095_idx',
            old_name='greedybear_ip_addr_tor_idx',
        ),
        migrations.AddField(
            model_name='ioc',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='greedybear.sensor'),
        ),
    ]
