# Generated by Django 4.2.20
# This file is a part of GreedyBear https://github.com/honeynet/GreedyBear
# See the file 'LICENSE' for copying permission.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0034_disable_additional_honeypots"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cowriecredential",
            unique_together={("session", "username", "password")},
        ),
    ]
