# Generated by Django 5.2.10 on 2026-02-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0034_remove_unused_log4pot'),
        ('greedybear', '0035_remove_ioc_sensor_country_code_and_more'),
    ]

    operations = [
    ]
