# Generated by Django 5.2.10 on 2026-02-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0035_merge_20260208_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ioc',
            name='attacker_country_code',
        ),
        migrations.RemoveField(
            model_name='ioc',
            name='sensor_country_code',
        ),
        migrations.RemoveField(
            model_name='ioc',
            name='sensor_country_name',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_country_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
