# Generated by Django 5.2.11 on 2026-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0035_rename_greedybear_ip_addr_tor_idx_greedybear__ip_addr_6bc095_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='greedybear.sensor'),
        ),
    ]
