# Generated by Django 4.2.20
# This file is a part of GreedyBear https://github.com/honeynet/GreedyBear
# See the file 'LICENSE' for copying permission.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0036_add_sensors_to_ioc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cowriesession",
            old_name="credentials",
            new_name="legacy_credentials",
        ),
        migrations.CreateModel(
            name="CowrieCredential",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, max_length=256)),
                ("password", models.CharField(blank=True, max_length=256)),
            ],
            options={
                "db_table": "greedybear_cowriecredential",
            },
        ),
        migrations.AddIndex(
            model_name="cowriecredential",
            index=models.Index(fields=["password"], name="cowriecred_pass_idx"),
        ),
        migrations.AddIndex(
            model_name="cowriecredential",
            index=models.Index(fields=["username", "password"], name="cowriecred_user_pass_idx"),
        ),
        migrations.AddField(
            model_name="cowriesession",
            name="credentials",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="greedybear.cowriecredential"
            ),
        ),
    ]
