# Generated by Django 5.2.11 on 2026-02-24 02:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0036_add_sensors_to_ioc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=64)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='greedybear.ioc')),
            ],
            options={
                'indexes': [models.Index(fields=['ioc', 'source'], name='greedybear__ioc_id_08377d_idx')],
            },
        ),
    ]
