# Generated by Django 4.2.20
# This file is a part of GreedyBear https://github.com/honeynet/GreedyBear
# See the file 'LICENSE' for copying permission.

from django.db import migrations, models


def migrate_credentials_data(apps, schema_editor):
    """Migrate credential data from ArrayField to separate CowrieCredential records."""
    CowrieSession = apps.get_model("greedybear", "CowrieSession")
    CowrieCredential = apps.get_model("greedybear", "CowrieCredential")

    batch_size = 1000
    credential_cache = {}

    for session in CowrieSession.objects.all().iterator(chunk_size=batch_size):
        legacy_creds = getattr(session, "legacy_credentials", []) or []
        credentials_to_add = []

        for cred_str in legacy_creds:
            if " | " in cred_str:
                username, password = cred_str.split(" | ", 1)
            else:
                username, password = "", cred_str

            username = username[:256]
            password = password[:256]
            key = (username, password)

            if key not in credential_cache:
                cred, _ = CowrieCredential.objects.get_or_create(
                    username=username,
                    password=password,
                )
                credential_cache[key] = cred

            credentials_to_add.append(credential_cache[key])

        if credentials_to_add:
            session.credentials.add(*credentials_to_add)


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0036_add_sensors_to_ioc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cowriesession",
            old_name="credentials",
            new_name="legacy_credentials",
        ),
        migrations.CreateModel(
            name="CowrieCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(blank=True, max_length=256)),
                ("password", models.CharField(blank=True, max_length=256)),
            ],
            options={
                "db_table": "greedybear_cowriecredential",
            },
        ),
        migrations.AddIndex(
            model_name="cowriecredential",
            index=models.Index(fields=["password"], name="cowriecred_pass_idx"),
        ),
        migrations.AddIndex(
            model_name="cowriecredential",
            index=models.Index(fields=["username", "password"], name="cowriecred_user_pass_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cowriecredential",
            unique_together={("username", "password")},
        ),
        migrations.AddField(
            model_name="cowriesession",
            name="credentials",
            field=models.ManyToManyField(blank=True, related_name="sessions", to="greedybear.cowriecredential"),
        ),
        migrations.RunPython(migrate_credentials_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="cowriesession",
            name="legacy_credentials",
        ),
    ]
