# Generated by Django 5.2.11 on 2026-02-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0036_add_sensors_to_ioc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shasum", models.CharField(max_length=64)),
                ("url", models.CharField(blank=True, default="", max_length=900)),
                (
                    "dst_filename",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="greedybear.cowriesession",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["shasum"], name="greedybear__shasum_de8dd5_idx")],
                "constraints": [models.UniqueConstraint(fields=("shasum", "session"), name="unique_download_per_session")],
            },
        ),
    ]
