# Generated by Django 5.2.11 on 2026-02-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0034_rename_generalhoneypot_honeypot_and_more"),
        ("greedybear", "0036_add_sensors_to_ioc"),
    ]

    operations = []
