# Generated by Django 5.2.11 on 2026-02-18 01:57

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0036_add_sensors_to_ioc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseIPDBFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=256, unique=True)),
                ('abuse_confidence_score', models.IntegerField(blank=True, null=True)),
                ('usage_type', models.CharField(blank=True, default='', max_length=64)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='greedybear__ip_addr_3145c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatFoxFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=256)),
                ('malware', models.CharField(blank=True, default='', max_length=128)),
                ('malware_printable', models.CharField(blank=True, default='', max_length=128)),
                ('threat_type', models.CharField(blank=True, default='', max_length=64)),
                ('confidence_level', models.IntegerField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), blank=True, default=list, size=None)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='greedybear__ip_addr_4421ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=64)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='greedybear.ioc')),
            ],
            options={
                'indexes': [models.Index(fields=['ioc'], name='greedybear__ioc_id_bfd10a_idx'), models.Index(fields=['source'], name='greedybear__source_9693bf_idx')],
            },
        ),
    ]
