# Generated by Django 5.2.8 on 2026-02-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0036_migrate_credentials_data"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="torexitnode",
            new_name="greedybear__ip_addr_6bc095_idx",
            old_name="greedybear_ip_addr_tor_idx",
        ),
        migrations.AlterField(
            model_name="cowriecredential",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
