# Generated by Django 5.2.11 on 2026-02-25 03:39

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0036_add_sensors_to_ioc"),
    ]

    operations = [
        migrations.CreateModel(
            name="CowrieFileTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_seen", models.DateTimeField(default=datetime.datetime.now)),
                ("last_seen", models.DateTimeField(default=datetime.datetime.now)),
                ("transfers", models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name="cowriesession",
            name="file_transfers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="greedybear.cowriefiletransfer",
            ),
        ),
    ]
