# Generated by Django 5.2.10 on 2026-02-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0036_merge_20260205_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ioc',
            name='attacker_country_code',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_country_code',
        ),
    ]
