# Generated by Django 5.2.10 on 2026-02-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0035_rename_greedybear_ip_addr_tor_idx_greedybear__ip_addr_6bc095_idx'),
        ('greedybear', '0037_remove_ioc_attacker_country_code_and_more'),
    ]

    operations = [
    ]
