# Generated by Django 4.2.20
# This file is a part of GreedyBear https://github.com/honeynet/GreedyBear
# See the file 'LICENSE' for copying permission.

from django.db import migrations


def migrate_credentials_to_m2m(apps, schema_editor):
    CowrieSession = apps.get_model("greedybear", "CowrieSession")
    CowrieCredential = apps.get_model("greedybear", "CowrieCredential")

    unique_credentials_map = {}

    for session in CowrieSession.objects.all().iterator(chunk_size=1000):
        legacy_creds = getattr(session, "legacy_credentials", []) or []

        for cred_str in legacy_creds:
            if " | " in cred_str:
                username, password = cred_str.split(" | ", 1)
            else:
                username, password = "", cred_str

            username = username[:256]
            password = password[:256]
            key = (username, password)

            if key not in unique_credentials_map:
                cred, _ = CowrieCredential.objects.get_or_create(
                    username=username,
                    password=password,
                )
                unique_credentials_map[key] = cred

    for session in CowrieSession.objects.all().iterator(chunk_size=1000):
        legacy_creds = getattr(session, "legacy_credentials", []) or []
        creds_to_add = []

        for cred_str in legacy_creds:
            if " | " in cred_str:
                username, password = cred_str.split(" | ", 1)
            else:
                username, password = "", cred_str

            username = username[:256]
            password = password[:256]
            key = (username, password)

            if key in unique_credentials_map:
                creds_to_add.append(unique_credentials_map[key])

        if creds_to_add:
            session.credentials.add(*creds_to_add)


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0038_add_unique_constraint_to_credentials"),
    ]

    operations = [
        migrations.RunPython(
            migrate_credentials_to_m2m, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="cowriesession",
            name="legacy_credentials",
        ),
    ]
