# Generated by Django 5.2.11 on 2026-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0038_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='attacker_country',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sensor',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='ioc',
            index=models.Index(fields=['attacker_country'], name='greedybear__attacke_2b9c7d_idx'),
        ),
    ]
