# Generated by Django 5.2.11 on 2026-03-03 09:27

import django.db.models.deletion
from django.db import migrations, models


def migrate_asn_to_autonomous_system(apps, schema_editor):
    IOC = apps.get_model('greedybear', 'IOC')
    AutonomousSystem = apps.get_model('greedybear', 'AutonomousSystem')

    for ioc in IOC.objects.all():
        if hasattr(ioc, 'asn') and ioc.asn is not None:
            as_obj, created = AutonomousSystem.objects.get_or_create(
                asn=ioc.asn,
                defaults={"name": ""}
            )
            ioc.autonomous_system = as_obj
            ioc.save(update_fields=['autonomous_system'])


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0039_ioc_attacker_country_sensor_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousSystem',
            fields=[
                ('asn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, blank=True)),
            ],
        ),

        migrations.AddField(
            model_name='ioc',
            name='autonomous_system',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='iocs',
                to='greedybear.autonomoussystem',
            ),
        ),

        migrations.RunPython(migrate_asn_to_autonomous_system),

        migrations.RemoveField(
            model_name='ioc',
            name='asn',
        ),
    ]