# Generated by Django 5.2.11 on 2026-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0039_ioc_attacker_country_sensor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='key',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
