# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0039_ioc_attacker_country_sensor_country_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['key'], name='greedybear__key_tag_idx'),
        ),
    ]
