# Generated by Django 5.2.11 on 2026-03-03 09:27

import django.db.models.deletion
from django.db import migrations, models


def migrate_asn_to_autonomous_system(apps, schema_editor):
    IOC = apps.get_model('greedybear', 'IOC')
    AutonomousSystem = apps.get_model('greedybear', 'AutonomousSystem')

    # gathering all unique ASN values from existing IOCs
    asns = (
        IOC.objects.exclude(asn__isnull=True)
        .values_list('asn', flat=True)
        .distinct()
    )

    # creating bulk AutonomousSystem objects for missing ASNs
    existing_asns = set(AutonomousSystem.objects.filter(asn__in=asns).values_list('asn', flat=True))
    to_create = [AutonomousSystem(asn=asn, name="") for asn in asns if asn not in existing_asns]
    if to_create:
        AutonomousSystem.objects.bulk_create(to_create)

    #  mapping ASN to AutonomousSystem object
    asn_map = {as_obj.asn: as_obj for as_obj in AutonomousSystem.objects.filter(asn__in=asns)}

    #  batch update IOCs in chunks to avoid massive single queries
    batch_size = 1000
    iocs_qs = IOC.objects.exclude(asn__isnull=True).iterator()
    batch = []
    for ioc in iocs_qs:
        ioc.autonomous_system = asn_map[ioc.asn]
        batch.append(ioc)
        if len(batch) >= batch_size:
            IOC.objects.bulk_update(batch, ['autonomous_system'])
            batch = []

    if batch:
        IOC.objects.bulk_update(batch, ['autonomous_system'])


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0040_alter_tag_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousSystem',
            fields=[
                ('asn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, blank=True)),
            ],
        ),

        migrations.AddField(
            model_name='ioc',
            name='autonomous_system',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='iocs',
                to='greedybear.autonomoussystem',
            ),
        ),

        migrations.RunPython(migrate_asn_to_autonomous_system),

        migrations.RemoveField(
            model_name='ioc',
            name='asn',
        ),
    ]