# Generated by Django 5.2.11 on 2026-03-03 09:27

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def migrate_asn_to_autonomous_system(apps, schema_editor):
    IOC = apps.get_model("greedybear", "IOC")
    AutonomousSystem = apps.get_model("greedybear", "AutonomousSystem")

    asns = IOC.objects.exclude(asn__isnull=True).values_list("asn", flat=True).distinct()

    AutonomousSystem.objects.bulk_create(
        [AutonomousSystem(asn=asn, name="") for asn in asns],
        ignore_conflicts=True,  # prevent duplicate asn without crashing
    )

    IOC.objects.exclude(asn__isnull=True).update(autonomous_system_id=F("asn"))


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0042_credential_model_and_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousSystem",
            fields=[
                ("asn", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="ioc",
            name="autonomous_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="iocs",
                to="greedybear.autonomoussystem",
            ),
        ),
        migrations.RunPython(
            migrate_asn_to_autonomous_system,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="ioc",
            name="asn",
        ),
    ]
