# Generated by Django 5.2.12 on 2026-03-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0043_autonomoussystem_remove_ioc_asn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomoussystem',
            name='expected_interactions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='expected_ioc_count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='ioc_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='total_attack_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='total_interaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autonomoussystem',
            name='total_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
