# Generated by Django 5.2.12 on 2026-03-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0043_autonomoussystem_remove_ioc_asn_and_more'),
        ('greedybear', '0043_cowriefiletransfer'),
    ]

    operations = [
    ]
