# Generated by Django 5.2.12 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0043_autonomoussystem_remove_ioc_asn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="protocol",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.RemoveConstraint(
            model_name="credential",
            name="unique_credential",
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.UniqueConstraint(
                fields=("username", "password", "protocol"),
                name="unique_credential",
            ),
        ),
    ]
