# Generated by Django 5.2.11 on 2026-03-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0043_autonomoussystem_remove_ioc_asn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional human-readable label to identify this sensor (e.g. 'home-pi', 'cloud-aws-eu').",
                max_length=128,
            ),
        ),
    ]