# Generated by Django 5.2.12 on 2026-03-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0046_sensor_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='credentials', to='greedybear.ioc'),
        ),
    ]
