# Generated by Django 5.2.12 on 2026-04-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0047_credential_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="ioc",
            name="attacker_country_code",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
