# Generated by Django 5.2.12 on 2026-03-17 00:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0048_add_attacker_country_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GeneralHoneypot",
            new_name="Honeypot",
        ),
        migrations.RemoveConstraint(
            model_name="honeypot",
            name="unique_generalhoneypot_name_ci",
        ),
        migrations.RenameField(
            model_name="ioc",
            old_name="general_honeypot",
            new_name="honeypots",
        ),
        migrations.AddConstraint(
            model_name="honeypot",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("name"), name="unique_honeypot_name_ci"),
        ),
    ]
