# Generated by Django 5.2.12 on 2026-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0049_rename_generalhoneypot_honeypot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttackerActivityBucket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attacker_ip", models.GenericIPAddressField()),
                ("feed_type", models.CharField(max_length=32)),
                ("bucket_start", models.DateTimeField()),
                ("interaction_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["bucket_start"], name="greedybear__bucket__ce4aaf_idx"),
                    models.Index(fields=["feed_type", "bucket_start"], name="greedybear__feed_ty_84e90b_idx"),
                    models.Index(fields=["attacker_ip", "bucket_start"], name="greedybear__attacke_910f2f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("attacker_ip", "feed_type", "bucket_start"), name="unique_attacker_activity_bucket"),
                ],
            },
        ),
    ]
