# Generated by Django 5.2.12 on 2026-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0049_rename_generalhoneypot_honeypot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttackerActivityBucket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attacker_ip", models.GenericIPAddressField()),
                ("feed_type", models.CharField(max_length=32)),
                ("bucket_start", models.DateTimeField()),
                ("interaction_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["bucket_start"], name="greedybear__bucket__ce4aaf_idx"),
                    models.Index(fields=["feed_type", "bucket_start"], name="greedybear__feed_ty_84e90b_idx"),
                    models.Index(fields=["attacker_ip", "bucket_start"], name="greedybear__attacke_910f2f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("attacker_ip", "feed_type", "bucket_start"), name="unique_attacker_activity_bucket"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrendingAttackerSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("window_minutes", models.IntegerField()),
                ("feed_type", models.CharField(max_length=32)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("attacker_ip", models.GenericIPAddressField()),
                ("current_interactions", models.IntegerField(default=0)),
                ("previous_interactions", models.IntegerField(default=0)),
                ("interaction_delta", models.IntegerField(default=0)),
                ("growth_score", models.FloatField(default=0)),
                ("current_rank", models.IntegerField(null=True)),
                ("previous_rank", models.IntegerField(null=True)),
                ("rank_delta", models.IntegerField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["window_minutes", "feed_type", "current_rank"], name="greedybear__window__f2275e_idx"),
                    models.Index(fields=["computed_at"], name="greedybear__compute_85b040_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("window_minutes", "feed_type", "attacker_ip"), name="unique_trending_snapshot_window_feed_ip"),
                ],
            },
        ),
    ]
