# Generated by Django 5.2.12 on 2026-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0050_attackeractivitybucket"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ioc",
            index=models.Index(fields=["attacker_country_code"], name="greedybear__attacke_29490b_idx"),
        ),
    ]
