# Generated by Django 5.2.12 on 2026-04-17 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0050_alter_statistics_source_length"),
        ("greedybear", "0050_attackeractivitybucket"),
    ]

    operations = []