# Generated by Django 5.2.12 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greedybear", "0049_rename_generalhoneypot_honeypot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="source",
            field=models.CharField(max_length=64),
        ),
    ]
