name: Composite action restore Python virtual environment
description: Composite action to restore Python virtual environment
inputs:
  virtual_environment_path:
    description: Path to where virtual environment will be restored.
    required: false
    default: ".venv"
  requirements_paths:
    description: Space separeted list of requirement files. They will be used to compute the hash for the cache key.
    required: true
  git_reference:
    description: A git reference (name of the branch, reference to the PR) that will be used to build the cache key.
    required: false
    default: ${{ github.ref_name }}
  python_version:
    description: Python version string to include in the cache key, preventing cross-version cache collisions.
    required: true

outputs:
  cache-hit:
    description: Whether virtual environment was found in the cache or not.
    value: ${{ steps.restore_virtual_environment.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Compute requirements files SHA256 hash
      id: compute_requirements_files_sha256_hash
      uses: ./.github/actions/misc/compute_files_hash
      with:
        file_paths: ${{ inputs.requirements_paths }}

    - name: Restore virtual environment
      id: restore_virtual_environment
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.virtual_environment_path }}
        key: ${{ inputs.git_reference }}-py${{ inputs.python_version }}-venv-${{ steps.compute_requirements_files_sha256_hash.outputs.computed_hash }}
    
    - name: Activate restored virtual environment
      if: >
        steps.restore_virtual_environment.outputs.cache-hit == 'true'
      uses: ./.github/actions/python_requirements/create_virtualenv
      with:
        virtualenv_path: ${{ inputs.virtual_environment_path }}
        activate_only: true